<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnfyhkq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnfyhkq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKnfyhkq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKnfyhkq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKnfyhkq\appProdProjectContainer([
    'container.build_hash' => 'Knfyhkq',
    'container.build_id' => '7a9e38a0',
    'container.build_time' => 1611842957,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnfyhkq');
